name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - name: Get package version
        id: get_version
        run: echo "::set-output name=version::$(node -p -e "require('./package.json').version")"      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghciutac/factory39wizards:${{ steps.get_version.outputs.version }}
      - name: Login to Docker
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login --username ghciutac --password-stdin
      - name: Deploy Image to DockerHub
        run: docker push ghciutac/factory39wizards:${{ steps.get_version.outputs.version }}
